### ISSUE TITLE
The name `QCARRenderer' does not exist in the current context

### ISSUE THREAD

**Issue by jsinoti** [tsubaki/GoogleCardboad_AR#1]
Hi, I created a project then import the Vuforia package and then paste the GoogleCardboard_AR on this folder, but I'm receiving this error. I don't know if it is a version problem. Can you support with it?

Tks

**Comment by jsinoti** [comment]
I tried use Vuforia.QCARRenderer, but it doesn't works, do you have some idea? 

Tks

**Comment by KisloTAooAnkit** [comment]
> I tried use Vuforia.QCARRenderer, but it doesn't works, do you have some idea?
> 
> Tks

Anyone Got any solution for this ?
